<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Categories extends CI_Controller 
{

	public function __construct()
	{
		parent::__construct();
		$this->load->library('instamojo');
		$this->load->model('Donation_model');
		$this->load->helper('url');
        
    
	}


	public function index()
	{



		

		// $this->load->library('instamojo');
		// $pay = $this->instamojo->pay_request( 

		// 				$amount = "200" , 
		// 				$purpose = "TEST" , 
		// 				$buyer_name = "rbbqq" , 
		// 				$email = "dharmarmepcoit@gmail.com" , 
		// 				$phone = "7708437644" ,
		//      			$send_email = 'TRUE' , 
		//      			$send_sms = 'TRUE' , 
		//      			$repeated = 'FALSE'

		//      		);

		// // print_r($pay);
		// $pay_url = $pay['longurl']   ;


		// redirect($pay_url,'refresh') ;

		// $this->load->view('don_inc/header');
          $this->load->view('welcome_message');
          // $this->load->view('don_inc/footer');
	}

	public function get_all()
	{
		$result = $this->instamojo->all_payment_request();

		print_r($result);
	}


	public function pay_request()
	{
		
		$this->load->library('instamojo');
		$pay = $this->instamojo->pay_request( 


						$amount = "200" , 
						$purpose = "TEST" , 
						$buyer_name = "rbbqq" , 
						$email = "rajeevbbqq@gmail.com" , 
						$phone = "89xxxx2017" ,
		     			$send_email = 'TRUE' , 
		     			$send_sms = 'TRUE' , 
		     			$repeated = 'FALSE'

		     		);


		$payment_id = $pay['id'];  // <= Payment Id
							      // print_r($pay) ; <=  Prints all the data from the request

	}

	


	public function status()
	{
		// $paymentId  = '84c04c212ccb4a8ba8c87e35ec4a2511'  ; // $paymentId generated by Instamojo
		
			$paymentId = $_GET["payment_request_id"];

		$status     = $this->instamojo->status($paymentId);

		print_r($status);
	}


	public function payment_status()
	{
		$requestId = '84c04c212ccb4a8ba8c87e35ec4a2511'  ;
		$status    = $this->instamojo->status($requestId);

		print_r($status) ;
	}


	public function show()
	{
		$data['request_id'] = '84c04c212ccb4a8ba8c87e35ec4a2511' ;
		$this->load->view('instamojo' ,$data);
	}


	// public function donation()
	// {
	// 	$this->load->view('don_inc/header');
 //          $this->load->view('donations/dashboard');
 //          $this->load->view('don_inc/footer');
	// }
	
	public function donation()
	{

		$result['type'] = $this->Donation_model->donation_type();

       $this->load->library('form_validation');
		$this->load->view('don_inc/donation_header');
          $this->load->view('donations/category',$result);
          $this->load->view('don_inc/footer');
	}

public function categories_view()
  {

    $id=($this->input->post('id'));

     $data = $this->Donation_model->categories_by_id($id);

     // print_r($data);

    if(empty($data))
    {

      // $this->session->set_flashdata('fail','Categories Details not added. First Addd the category');
      //                   redirect('admin/donation/categories');
    }
    else
    {
        foreach ($data as $result) 
        {
            $data_set[] = array("id"=>$result->id,
                  "purpose"=>$result->purpose,
                  "amount"=>$result->amount_detail,
                  "details"=>$result->details, 
                  );

        }
                
        // print_r($data_set);

      echo json_encode($data_set);
      exit();


    }
    
  } 


	public function registration()
	{

		

		$result['type'] = $this->Donation_model->donation_type();
		$this->session->set_flashdata('formType','registration');
     $this->load->library('form_validation');
	 $this->load->view('don_inc/donation_header');
     $this->load->view('donations/registration');
    // $this->load->view('don_inc/footer',);
	}
	
}





/* End of file example.php */
/* Location: ./application/controllers/example.php */
